# Generated by Django 5.2.11 on 2026-02-07 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0, help_text='Display order on homepage (lower numbers first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('video_type', models.CharField(choices=[('movie', 'Movie'), ('series', 'TV Series'), ('documentary', 'Documentary'), ('short', 'Short Film')], default='movie', max_length=20)),
                ('thumbnail', models.URLField(help_text='Thumbnail image URL (300x450px recommended)')),
                ('hero_image', models.URLField(blank=True, help_text='Hero banner image URL (1920x1080px)')),
                ('video_url', models.URLField(help_text='Video file URL or streaming link')),
                ('trailer_url', models.URLField(blank=True, help_text='Trailer video URL')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('duration_minutes', models.IntegerField(help_text='Duration in minutes')),
                ('rating_percentage', models.IntegerField(help_text='Rating as percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('age_rating', models.CharField(choices=[('G', 'G - General'), ('PG', 'PG - Parental Guidance'), ('PG-13', 'PG-13'), ('R', 'R - Restricted'), ('NC-17', 'NC-17')], default='PG', max_length=10)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200)),
                ('director', models.CharField(blank=True, max_length=100)),
                ('cast', models.CharField(blank=True, help_text='Comma-separated cast names', max_length=500)),
                ('language', models.CharField(default='English', max_length=50)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in hero banner')),
                ('is_active', models.BooleanField(default=True)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(related_name='videos', to='netflix.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
