# Generated by Django 4.2.7 on 2026-02-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='ai_content_tags',
            field=models.TextField(blank=True, help_text='AI-generated content tags for improved search'),
        ),
        migrations.AddField(
            model_name='video',
            name='ai_recommendation_score',
            field=models.FloatField(default=0.0, help_text='AI-calculated recommendation score (0-100)'),
        ),
    ]
